sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - python setup.py clean --all
  - python setup.py install

script:
  - python setup.py test

matrix:
  allow_failures:
    - python: 3.7