sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install codecov
  - pip install coverage
  - python setup.py clean --all
  - python setup.py install

script:
  - coverage run setup.py test


after_success:
  codecov