sudo: false

language: python

matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial  # Work around for 3.7 issues with Travis
      sudo: true    # See Github issue: https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
    - python: "pypy3"

install:
  - pip install --upgrade pip
  - pip install codecov
  - pip install coverage
  - python setup.py clean --all
  - python setup.py install

script:
  - coverage run setup.py test

after_success:
  codecov
