sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install codecov
  - python setup.py clean --all
  - python setup.py install

script:
  - python setup.py test

after_success:
  codecov